// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TGClientDownloadDAL;

#nullable disable

namespace TGClientDownloadDAL.Migrations
{
    [DbContext(typeof(TGDownDBContext))]
    [Migration("20240126174830_TGChannelCreated")]
    partial class TGChannelCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TGClientDownloadDAL.Entities.TgChannel", b =>
                {
                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<long>("AccessHash")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChannelId", "AccessHash");

                    b.ToTable("TgChannel");
                });
#pragma warning restore 612, 618
        }
    }
}
